import Link from "next/link";

import { AdminPagination } from "@/components/admin/admin-pagination";

import type { AccountInboxItem } from "@/server/account/queries";

export function AccountInbox({ items, page, pageSize, totalCount, search }: { items: AccountInboxItem[]; page: number; pageSize: number; totalCount: number; search: string }) {
  return <div className="space-y-4"><form className="flex flex-col gap-3 sm:flex-row" method="get"><input name="inboxSearch" defaultValue={search} aria-label="Search account updates" className="h-12 min-w-0 flex-1 appearance-none rounded-2xl border border-white/10 bg-stone-900/80 px-4 py-3 text-sm leading-6 text-white" placeholder="Search updates" /><input name="inboxPageSize" type="hidden" value={pageSize} readOnly /><button className="h-12 w-full shrink-0 rounded-full bg-white/10 px-5 py-3 text-sm font-medium leading-6 text-white transition hover:bg-white/15 sm:w-auto" type="submit">Search</button></form>{!items.length ? <p className="rounded-2xl border border-white/10 bg-stone-950/40 p-5 text-sm text-stone-400">{search ? "No updates match your search." : "You have no booking or payment updates yet."}</p> : <div className="space-y-3">{items.map((item) => <article key={item.id} className="rounded-2xl border border-white/10 bg-stone-950/40 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-medium text-white">{item.title}</p><p className="mt-1 text-sm leading-6 text-stone-300">{item.message}</p></div>{item.isActionRequired && item.href ? <Link className="shrink-0 rounded-full bg-amber-400 px-4 py-2 text-center text-sm font-medium text-stone-950 hover:bg-amber-300" href={item.href}>{item.actionLabel}</Link> : null}</div><p className="mt-3 text-xs text-stone-500">{item.createdAt.toLocaleString("en-PH", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Manila" })}</p></article>)}</div>}<AdminPagination basePath="/account" page={page} pageSize={pageSize} totalCount={totalCount} pageParam="inboxPage" pageSizeParam="inboxPageSize" /></div>;
}
